### ISSUE TITLE
The XML parser converts plus signs into spaces

### ISSUE THREAD

**Issue by zozlak** [sweetyrdf/easyrdf#15]
In the https://github.com/sweetyrdf/easyrdf/blob/master/lib/Parser/RdfXml.php#L803 `$data` should be URL encoded first (see https://www.php.net/manual/en/wrappers.data.php#100979).

Pull request on its way, just wanted an issue number to follow test names convention.

**Comment by k00ni** [comment]
*Discussions around this issue are in the PR #16*
